### ISSUE TITLE
UnsatisfiedLinkError 

### ISSUE THREAD

**Issue by Dhanush-S** [TrekDev/Xamarin.Android.Skobbler#1]
Hi,

Just started with skobbler and when I try to run the demo app I am getting the following error : 

`java.lang.UnsatisfiedLinkError: Couldn't load ngnative from loader dalvik.system.PathClassLoader[dexPath=/data/app/Skobbler.SdkDemo-1.apk,libraryPath=/data/app-lib/Skobbler.SdkDemo-1]: findLibrary returned null
at java.lang.Runtime.loadLibrary(Runtime.java:358)
at java.lang.System.loadLibrary(System.java:526)
at com.skobbler.ngx.versioning.SKVersioningManager.<clinit>(SourceFile:29)
at skobbler.sdkdemo.activities.SplashActivity.n_onCreate(Native Method)
at skobbler.sdkdemo.activities.SplashActivity.onCreate(SplashActivity.java:35)
at android.app.Activity.performCreate(Activity.java:5458)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2470)
at android.app.ActivityThread.access$900(ActivityThread.java:174)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1307)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5593)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
at dalvik.system.NativeStart.main(Native Method)`

Am I missing something here in terms of initialization? Any direction in solving this will be a great help.

Thanks!!

**Comment by jeremy-ellis-tech** [comment]
Hi Dhanush-S,

May I ask what device and build configuration you're using?

-TD

**Comment by Dhanush-S** [comment]
Hi,

Thanks for quick reply.
I am using Samsung Tab 3(android 4.4.2) device and tried in API 10 emulator.
I am using AnyCPU configuration.I am using Mac for development.Should I initialize some settings or am I missing something here?

Thanks.

**Comment by Dhanush-S** [comment]
Hi,

After some hours of frustration I came to know that the binding project's target framework was set to 4.0.After setting it to 2.3 it started working for me in the application.

Thanks.

**Comment by jeremy-ellis-tech** [comment]
Hi Dhanush-S,

Glad to hear you have it working now.
The binding project target framework should be 2.3 as it is set in the csproj file.
Is the reason that it wasn't working because you changed it yourself?

-TD

**Comment by Dhanush-S** [comment]
Hi TrekDev,

Yes,after changing the binding project's target framework to 2.3 it started working for me.
One quick question,does NearBySearch work with skobbler sdk,coz I keep getting the search result count to be 0 in my application.Checked with the Sdk Demo project,there also I am getting the count to be 0.Is it problem with my skobbler sdk or my implementation?Any pointers is useful.

Thanks.

**Comment by jeremy-ellis-tech** [comment]
Hi Dhanush-S,

Have you added your API key to the demo project?

In SplashActivity.cs you have to replace `private const string ApiKey = "API_KEY_HERE";` with your Mobile API key provided to you by Skobbler. You can find your key by signing in to [Skobbler](http://www.skobbler.com) and checking [your api keys](http://developer.skobbler.com/apikeys)

**Comment by Dhanush-S** [comment]
Hi TrekDev,

Yes,I had forgot to put API_KEY in demo application.It successfully gave the results for search.But in my application it is still giving the result count to be 0.I checked everything right from implementation and all the application settings and manifest,but no clue.Any ideas where I could be going wrong.

Thanks.

**Comment by jeremy-ellis-tech** [comment]
Hi Dhanush-S,

My only guess would be initialisation of the SDK. Take a look at the demo application [SplashActivity.cs](https://github.com/TrekDev/Xamarin.Android.Skobbler/blob/master/Skobbler.SdkDemo/Activities/SplashActivity.cs#L118).

Other than that I can't really help you because I don't know what it is you are doing, or any warning/errors it is giving you. The result of `SearchManager.NearbySearch()` will give you a `SKSearchStatus` which will tell you if/why it is failing. If you post your relevant code as a gist I might have a better chance of helping.

-TD

**Comment by jeremy-ellis-tech** [comment]
I'll assume you've found a solution since you haven't responded in a while.

If you're still having problems please open another issue with some specific details about your problem.
